---
# tasks file for vagrant-plugins

- name: check if vagrant is installed
  shell: which vagrant
  register: if_vagrant_installed
  failed_when: if_vagrant_installed.rc not in [0,1]

- name: install vagrant plugins
  shell: vagrant plugin install {{ item }} 
  with_items: vagrant_plugins_plugins

- name: install vagrant plugins with version
  shell: vagrant plugin install {{ item.name }} --plugin-version {{ item.version}} 
  with_items: vagrant_plugins_plugins_with_version
