---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: ${PROVIDER_NAME-virtualbox}
    driver: kvm # Ignored by virtualbox
    options:
      memory: 2048
      cpus: 1
lint:
  name: yamllint
  enabled: false
platforms:
  - name: instance
    box: ${MOLECULE_DISTRO_BOX-generic/ubuntu2004}
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
verifier:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
